// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewSystem struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Os   string `json:"os"`
}

type System struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Os   string `json:"os"`
}
